#!/usr/bin/env bash
# Bash sript that transfers a file from our client to a server.
#FILE_TRANS is $1
#IP_SERVER is $2
#USERNAME is $3
#PATH_SSH is $4 is the ~/.ssh/holberton .

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    file="$1"; server="$2"; username="$3"; key="$4"
    scp "-i" "$key" "-o" "StrictHostKeyChecking=False" "$file" "$username@$server:~/"
fi
