#!/usr/bin/env bash
# Installs nginx on your web server and add a custom HTTP header.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
file="/etc/nginx/sites-available/default"
config="add_header X-Served-By $HOSTNAME;\n"
sudo sed -i "19i $config" "$file"
sudo service nginx restart
