#!/usr/bin/env bash
#ufw config

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y ufw
#command to allow connections on a specific port (allow)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
#enable firewall
sudo ufw enable
#check UFW status
sudo ufw status verbose
