#!/usr/bin/env bash
# Resolves and changes the locahost.
# Resolves and changes the Facebook.
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo '8.8.8.8     facebook.com' >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
